# Generated by Django 3.2 on 2022-07-29 18:37

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize'),
        ),
    ]
