# Generated by Django 3.2 on 2022-06-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_model_product_model_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_no',
        ),
    ]
