# Generated by Django 3.2 on 2022-07-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['-created_at']},
        ),
    ]
