# Generated by Django 3.2 on 2022-06-21 03:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c38b700-0744-40be-8893-54711f8d1884'), editable=False, primary_key=True, serialize=False),
        ),
    ]
