# Generated by Django 3.2 on 2022-06-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_address_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
