# Generated by Django 3.2 on 2022-06-18 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('a194ce46-30ea-4cb4-85bd-cc5e53cc66a9'), editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistilledWater',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('a194ce46-30ea-4cb4-85bd-cc5e53cc66a9'), editable=False, primary_key=True, serialize=False)),
                ('size', models.FloatField(choices=[('Select Size', ''), ('2.5', 2.5), ('5', 5), ('10', 10)], default='')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineOil',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('a194ce46-30ea-4cb4-85bd-cc5e53cc66a9'), editable=False, primary_key=True, serialize=False)),
                ('size', models.PositiveIntegerField(choices=[('Select Size', ''), ('500', 500), ('800', 800), ('900', 900), ('1000', 1000)], default='')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
