# Generated by Django 3.2 on 2022-06-21 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='model_no',
        ),
        migrations.AlterField(
            model_name='battery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distilledwater',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distilledwater',
            name='size',
            field=models.FloatField(choices=[('', 'Select Size'), (2.5, '2.5'), (5, '5'), (10, '10')], default=''),
        ),
        migrations.AlterField(
            model_name='engineoil',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='engineoil',
            name='size',
            field=models.PositiveIntegerField(choices=[('', 'Select Size'), (500, '500'), (800, '800'), (900, '900'), (1000, '1000')], default=''),
        ),
    ]
