# Generated by Django 3.2 on 2022-06-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20220621_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distilledwater',
            name='size',
            field=models.FloatField(choices=[('', 'Select Size'), (2, '2'), (5, '5'), (10, '10')], default=''),
        ),
    ]
