# Generated by Django 3.2 on 2022-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_distilledwater_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images'),
        ),
        migrations.AddField(
            model_name='distilledwater',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images'),
        ),
        migrations.AddField(
            model_name='engineoil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images'),
        ),
    ]
