# Generated by Django 3.2 on 2022-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20220623_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='model_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
