# Generated by Django 3.2 on 2022-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_battery_model_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distilledwater',
            name='size',
        ),
        migrations.RemoveField(
            model_name='engineoil',
            name='size',
        ),
        migrations.AddField(
            model_name='engineoil',
            name='model_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
