# Generated by Django 3.2 on 2022-07-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productcategory_options'),
        ('asset', '0007_auto_20220626_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='distilledwater',
            name='image',
        ),
        migrations.RemoveField(
            model_name='engineoil',
            name='image',
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('model_no', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
