# Generated by Django 3.2 on 2022-08-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sale.customerdetail'),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='handover_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='new_serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterywarrantyclaim',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('Received', 'Received'), ('Send to Company', 'Send to Company'), ('Returned OK', 'Returned_OK'), ('F.O.C.', 'F.O.C.'), ('Handover to Customer', 'Handover to Customer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batterywarrantyclaim',
            name='transport',
            field=models.CharField(blank=True, choices=[('', 'Select Transport'), ('Dealer Vehicle', 'Dealer Vehicle'), ('Bus', 'Bus')], max_length=50, null=True),
        ),
    ]
