# Generated by Django 3.2 on 2022-07-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batterywarrantyclaim',
            options={'ordering': ['-created_at']},
        ),
    ]
