# Generated by Django 3.2 on 2022-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20220806_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterywarrantyclaim',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('Received', 'Received'), ('Send to Company', 'Send to Company'), ('Returned OK', 'Returned OK'), ('F.O.C.', 'F.O.C.'), ('Handover to Customer', 'Handover to Customer')], max_length=50, null=True),
        ),
    ]
