# Generated by Django 3.2 on 2022-08-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_batterywarrantyclaim_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterywarrantyclaim',
            name='claim_success',
            field=models.BooleanField(default=False),
        ),
    ]
