# Generated by Django 3.2 on 2022-07-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='CustomerDetail',
        ),
    ]
