# Generated by Django 3.2 on 2022-07-29 18:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsize_size'),
        ('sale', '0002_rename_customerdetails_customerdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
