# Generated by Django 3.2 on 2022-07-29 19:06

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_size'),
        ('sale', '0005_auto_20220730_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
