# Generated by Django 3.2 on 2022-07-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
