# Generated by Django 3.2 on 2022-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20220731_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
