# Generated by Django 3.2 on 2022-07-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_sale_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
